language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
# command to install dependencies
install:
    - travis_retry pip install -r requirements-dev.txt
    - pip install -e .
    # unicode bug with coverage on python 3.2, must use coverage 3.7.1
    # https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
# command to run tests
script:
- nosetests
- nosetests --with-coverage
