language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- travis_retry pip install -r requirements-dev.txt
- pip install -e .
- if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
script:
- nosetests
- nosetests --with-coverage
- python setup.py sdist bdist_wheel
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 5/s0vQp3qmyE3lg38a1zTQM+HyUS0fnegvNHy3kh7cBacX60HakLmSA+NlUZX/epxHSb6eUJTg00ZCg89oOH5WWGPNkMRk3302MKWtNZXabR4JcOspGVnM9XBVpT+E3EDZumlC6p5YrX89QueelU0Isd/9AY1pbPxjAqMGgAPcuuKxWbxTYBkHBSIdm1xpU/P8PlFBtIJaeCgsZr72/AmuYXjb0gfVDoVaJa5hdj8gG47kWK3N4mwU+yh+A6BjUeuEUaUy2QYSK3KaB1AGw9w+6cZb0Odx6frrzdUx2sUP8yAxSIUgEjcygG9fy8ZUiwxJtyTzqIxx+1ssdp6oNVJzwWSaDVQE4l7GtipV+iEMr247LlChs+z7tNElYyZhZRj9rwqUwaNzlwIrIAf7zIuhZRH6G8b/8wka9RIMo7m+ivyVF2RiDjatqchE1BDClUrEdpWIzXRQywiPehDsmDOHGe2PaFdb8QFjdP2Q2onWg4Y7ou6LTPUFrqy0Oz0J8tvPdyliNsIW9crZjibJhx2ChbjMU8QxyzjlU17lhsHOeRR60NbZu0n5ZRkULMFycsRzwAE6CbyU8IktjQIRlXhjfAd0JSNqFvq8S17x51yjBU/sOmeJwfqMKQY2beuCaNhcJj5HksvKNmrc4zGPk6oiOJvbpm7KDQh0pCRKrewks=
  file: dist/*
  on:
    repo: robodair/pydocstring
